### ISSUE TITLE
Correction of a small spelling problem

### ISSUE THREAD

**Issue by CuiZewen** [scala-lms/tutorials#11]
hi, i find a small spelling problem:
in las-tutorials/src/data/README.md , we should use n_grCam instead of n_gram 

Right:

`mysql>select * from 1gram_a where n_grCam = 'Auswanderung'`

`mysql> select n_grCam, match_count from 1gram_a where n_grCam = 'Auswanderung';`

Error:

`mysql>select * from 1gram_a where n_gram = 'Auswanderung'`

`mysql> select n_gram, match_count from 1gram_a where n_gram = 'Auswanderung'`

thank you   (^-^)

**Comment by TiarkRompf** [comment]
Not sure I understand -- are you suggestion `n_gram` should be changed to `n_grCam`? Why? (Maybe I'm missing what's the error here)

**Comment by CuiZewen** [comment]
I'm sorry for my carelessness. I made a spelling mistake myself. I'll be careful next time
there is nothing wrong in README.
