### ISSUE TITLE
Sharing the implementation between interpreted and staged versions

### ISSUE THREAD

**Issue by fsulima** [scala-lms/tutorials#5]
Regarding SQL compiler example: in your opinion, what would it take to make it possible to share code between interpreted and staged implementations (applying a DRY principle)? In my case it would be interesting to be able to execute stuff in current runtime to see the result before generating something.

**Comment by TiarkRompf** [comment]
For discussions like this, the mailing list (delite-devel@googlegroups.com) is a better place than the issue tracker.
